# Generated by Django 5.2 on 2025-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mood', models.CharField(choices=[('chill', 'Chill'), ('romantic', 'Romantic'), ('heartbreak', 'Heartbreak'), ('soulful', 'Soulful'), ('classic', 'Classic'), ('old-but-gold', 'Old But Gold')], max_length=50)),
                ('language', models.CharField(choices=[('hindi', 'Hindi')], default='hindi', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='song_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
